settings:
  cache-size: 1024 # maximum entries in rate-limiter cache
  handshake-timeout: 3 # time in seconds to wait for a handshake packet from client
  client-buffer-limit: 64 # close connection if client doesn't send expected data within the first 64 bytes
  backend-buffer-limit: 4096 # close connection if backend doesn't send expected data within the first 4096 bytes
  rate-limit-window: 60 # reset rate limit counter after 60 seconds
  rate-limit: 5 # allow max 5 connections from single IP address within rate-limit-window
  concurrent-limit: 5 # allow max 5 concurrent connections from single IP address
  clients-limit: 200 # allow max total 200 concurrent connections
  listen: 25565
  log: connection

endpoints:
  server1:
    host: mc1.example.com # hostname used by client to connect to the server
    backend: 127.0.0.1:3000 # Minecraft server to forward traffic to
  server2:
    host: mc2.example.com
    backend: 127.0.0.1:3001
    motd: This is rewritten motd, {players} players online
  server2alias:
    host: coolserver.com
    rewrite: mc2.example.com # modify hostname in the handshake packet, mcproxy automatically resolves backend address from the referenced endpoint
  _default:
    motd: THIS IS FALLBACK STATUS # custom motd
    message: Sorry this server is not available. Try connecting to mc1.example.com # message on join
  _default2: # alternative fallback endpoint - rename to _default
    rewrite: mc1.example.com # fallback to server1

blocklist:
  - 192.168.1.5 # block ip from all endpoints
